from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('disciplinas/', views.disciplinas_list, name='disciplinas'),
    path('disciplinas/nova/', views.disciplina_create, name='disciplina_add'),
    path('disciplinas/<int:pk>/editar', views.disciplina_update, name='disciplina_edit'),
    path('disciplinas/<int:pk>/deletar', views.disciplina_delete, name='disciplina_delete'),
    path('flashcards/', views.flashcards_list, name='flashcards'),
    path('flashcards/nova/', views.flashcard_create, name='flashcard_add'),
    path('flashcards/<int:pk>/editar', views.flashcard_update, name='flashcard_edit'),
    path('flashcards/<int:pk>/deletar', views.flashcard_delete, name='flashcard_delete'),
    path('anotacoes/', views.anotacoes_list, name='anotacoes'),
    path('anotacoes/nova/', views.anotacao_create, name='anotacao_add'),
    path('anotacoes/<int:pk>/editar', views.anotacao_update, name='anotacao_edit'),
    path('anotacoes/<int:pk>/deletar', views.anotacao_delete, name='anotacao_delete'),
    path('calendario/', views.calendario_view, name='calendario'),
    path('calendario/novo', views.evento_create, name='evento_add'),
    path('calendario/<int:pk>/editar/', views.evento_update, name='evento_edit'),
    path('calendario/<int:pk>/delete/', views.evento_delete, name='evento_delete'),
    path('calendario/<int:pk>/concluir/', views.evento_concluir, name='evento_concluir'),
    path('refeicoes/', views.refeicoes_list, name='refeicoes'),
    path('receitas/', views.receitas_list, name='receitas'),
    path('receita/nova/', views.receita_create, name='receita_add'),
    path('receitas/<int:pk>/editar/', views.receita_update, name='receita_edit'),
    path('receitas/<int:pk>/deletar/', views.receita_delete, name='receita_delete'),
    path('lembretes/', views.lembretes_list, name='lembretes'),
    path('lembretes/novo/', views.lembrete_create, name='lembrete_add'),
    path('lembretes/<int:pk>/editar/', views.lembrete_update, name='lembrete_edit'),
    path('lembretes/<int:pk>/delete/', views.lembrete_delete, name='lembrete_delete'),
    path('relaxamento/', views.relaxamento_list, name='relaxamento'),
    path('relaxamento/novo/', views.relaxamento_create, name='relaxamento_add'),
    path('relaxamento/<int:pk>/editar/', views.relaxamento_update, name='relaxamento_edit'),
    path('relaxamento/<int:pk>/delete/', views.relaxamento_delete, name='relaxamento_delete'),
    path('motivacional/', views.motivacional_list, name='motivacional'),
    path('motivacional/add/', views.motivacional_create, name='motivacional_add'),
    path('motivacional/<int:pk>/editar/', views.motivacional_update, name='motivacional_edit'),
    path('motivacional/<int:pk>/delete/', views.motivacional_delete, name='motivacional_delete'),
    path('mural/', views.mural_view, name='mural'),
    path('mural/<int:pk>/editar/', views.mural_update, name='recado_edit'),
    path('mural/<int:pk>/excluir/', views.mural_delete, name='recado_delete'),
    path('settings/', views.settings_view, name='settings'),
    path('account/', views.account_view, name='account'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]