# Generated by Django 5.2 on 2025-04-03 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeRelaxamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('duracao', models.IntegerField(help_text='Duração em minutos')),
            ],
            options={
                'verbose_name': 'Atividade de Relaxamento',
                'verbose_name_plural': 'Atividades de Relaxamento',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('periodo', models.IntegerField()),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pausa', 'Pausa'), ('agua', 'Hidratação'), ('alongamento', 'Alongamento'), ('outro', 'Outro')], max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('intervalo', models.IntegerField(help_text='Intervalo em minutos')),
                ('dias_semana', models.CharField(help_text='String de 7 caracteres (0/1) para cada dia semana', max_length=7)),
                ('mensagem', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MensagemMotivacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('autor', models.CharField(default='Você', max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('agendada_para', models.DateTimeField(blank=True, null=True)),
                ('entregue', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensagem Motivacional',
                'verbose_name_plural': 'Mensagens Motivacionais',
            },
        ),
        migrations.CreateModel(
            name='PlanejamentoRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('cafe_manha', models.CharField(blank=True, max_length=200)),
                ('almoco', models.CharField(blank=True, max_length=200)),
                ('jantar', models.CharField(blank=True, max_length=200)),
                ('lanches', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Planejamento de Refeição',
                'verbose_name_plural': 'Planejamento de Refeições',
            },
        ),
        migrations.CreateModel(
            name='RecadorMural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('tempo_preparo', models.IntegerField(help_text='Tempo em minutos')),
                ('dificuldade', models.CharField(choices=[('fácil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], max_length=50)),
                ('valor_nutricional', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('aula', 'Anotação de Aula'), ('caso', 'Caso Clínico'), ('resumo', 'Resumo')], max_length=50)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='study_companion.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('prova', 'Prova'), ('trabalho', 'Trabalho'), ('plantao', 'Plantão'), ('outro', 'Outro')], max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='study_companion.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('dificuldade', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil')])),
                ('ultima_revisao', models.DateTimeField(blank=True, null=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard', to='study_companion.disciplina')),
            ],
        ),
    ]
