# Generated by Django 5.1.7 on 2025-04-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_companion', '0002_rename_recadormural_recadomural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='periodo',
            field=models.IntegerField(choices=[(1, '1° Período'), (2, '2° Período'), (3, '3° Período'), (4, '4° Período'), (5, '5° Período'), (6, '6° Período'), (7, '7° Período'), (8, '8° Período'), (9, '9° Período'), (10, '10° Período'), (11, '11° Período'), (12, '12° Período')]),
        ),
    ]
