# Generated by Django 5.2 on 2025-04-11 14:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_companion', '0004_disciplina_cor_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacao',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
