# Generated by Django 5.2 on 2025-04-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_companion', '0005_alter_anotacao_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='dificuldade',
            field=models.IntegerField(choices=[(1, 'facil'), (2, 'medio'), (3, 'dificil')]),
        ),
    ]
