# Generated by Django 5.1.7 on 2025-04-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_companion', '0006_alter_flashcard_dificuldade'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
