# Generated by Django 5.1.7 on 2025-04-25 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_companion', '0007_eventocalendario_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamentorefeicao',
            name='almoco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almocos', to='study_companion.receita'),
        ),
        migrations.AlterField(
            model_name='planejamentorefeicao',
            name='cafe_manha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafe_manha', to='study_companion.receita'),
        ),
        migrations.AlterField(
            model_name='planejamentorefeicao',
            name='jantar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jantares', to='study_companion.receita'),
        ),
        migrations.AlterField(
            model_name='planejamentorefeicao',
            name='lanches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lanches', to='study_companion.receita'),
        ),
    ]
