# Generated by Django 5.1.7 on 2025-04-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_companion', '0009_alter_planejamentorefeicao_almoco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamentorefeicao',
            name='almoco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planejamentorefeicao',
            name='cafe_manha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planejamentorefeicao',
            name='jantar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planejamentorefeicao',
            name='lanches',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
