# Generated by Django 5.1.7 on 2025-04-25 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_companion', '0011_alter_planejamentorefeicao_almoco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamentorefeicao',
            name='almoco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_almoco', to='study_companion.receita'),
        ),
        migrations.AlterField(
            model_name='planejamentorefeicao',
            name='cafe_manha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_cafe_manha', to='study_companion.receita'),
        ),
        migrations.AlterField(
            model_name='planejamentorefeicao',
            name='jantar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_jantar', to='study_companion.receita'),
        ),
        migrations.AlterField(
            model_name='planejamentorefeicao',
            name='lanches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planejamentos_lanches', to='study_companion.receita'),
        ),
    ]
