# Generated by Django 5.1.7 on 2025-04-25 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_companion', '0013_alter_planejamentorefeicao_almoco_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Desativar verificação de chave estrangeira temporariamente
            PRAGMA foreign_keys = OFF;
            
            -- Criar tabela temporária com estrutura correta
            CREATE TABLE "temp_study_companion_planejamentorefeicao" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "dia_semana" integer NOT NULL,
                "cafe_manha_id" integer NULL REFERENCES "study_companion_receita" ("id") DEFERRABLE INITIALLY DEFERRED,
                "almoco_id" integer NULL REFERENCES "study_companion_receita" ("id") DEFERRABLE INITIALLY DEFERRED,
                "jantar_id" integer NULL REFERENCES "study_companion_receita" ("id") DEFERRABLE INITIALLY DEFERRED,
                "lanches_id" integer NULL REFERENCES "study_companion_receita" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            
            -- Copiar dados (definindo todos os valores problemáticos como NULL)
            INSERT INTO "temp_study_companion_planejamentorefeicao" ("id", "dia_semana", "cafe_manha_id", "almoco_id", "jantar_id", "lanches_id")
            SELECT 
                "id", 
                "dia_semana", 
                NULL,  -- Defina todos como NULL para evitar problemas de integridade
                NULL, 
                NULL, 
                NULL 
            FROM "study_companion_planejamentorefeicao";
            
            -- Remover tabela antiga
            DROP TABLE "study_companion_planejamentorefeicao";
            
            -- Renomear a tabela temporária
            ALTER TABLE "temp_study_companion_planejamentorefeicao" RENAME TO "study_companion_planejamentorefeicao";
            
            -- Reativar verificação de chave estrangeira
            PRAGMA foreign_keys = ON;
            """,
            reverse_sql="SELECT 1;"  # Um comando simples para migração reversa
        ),
    ]