# Generated by Django 5.1.7 on 2025-04-25 00:49

from django.db import migrations

def mark_as_done(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('study_companion', '0014_fix_nullable_fields'),
    ]

    operations = [
        migrations.RunPython(mark_as_done),
    ]   
