# Generated by Django 5.1.7 on 2025-04-25 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_companion', '0015_fix_table_structure'),
    ]

    operations = [
    ]
