# Generated by Django 5.1.7 on 2025-04-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_companion', '0016_fixed_foreign_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='dificuldade',
            field=models.IntegerField(choices=[(1, 'Fácil'), (2, 'Médio'), (3, 'Difícil')]),
        ),
    ]
