# Generated by Django 5.1.7 on 2025-04-29 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_companion', '0017_alter_flashcard_dificuldade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recadomural',
            name='autor',
        ),
        migrations.AddField(
            model_name='recadomural',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recados_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recadomural',
            name='remetente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recados_enviados', to=settings.AUTH_USER_MODEL),
        ),
    ]
